[package]
name = "well-i-known-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
well-i-known-server = { path = "../server" }
clap = { version = "4.5.4", features = ["derive"] }

[[bin]]
name = "wellik"
path = "src/main.rs"
