[package]
name = "well-i-known-core"
version = "0.1.0"
edition = "2021"

[dependencies]
indoc = "2"
rsa = "0.9.6"
rand = "0.8.5"
base64 = "0.21.5"
anyhow = "1.0"

# faster RSA key gen
[profile.dev.package.num-bigint-dig]
opt-level = 3